# Generated by Django 5.1.1 on 2024-09-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_genre_animation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animation',
            name='genre',
            field=models.ManyToManyField(related_name='articles', to='articles.genre'),
        ),
    ]
